-- ============================================================================
-- Homeowner app, part 2 of 3: SEED - the launch catalogue.
-- GENERATED by db/gen-seed.mjs from src/lib/catalogue.data.json. Do not edit
-- by hand; edit the JSON and regenerate. Idempotent: re-running replaces
-- each package's children and upserts the package row.
-- ============================================================================
begin;

-- Water heater replacement
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('water_heater', 'Water heater replacement', 'Water heater', 'replacement', 'Plumbing', 'front', 'priced', 218000, '40-gallon gas, installed in the same spot',
        true, 10, true, null, 'water_heater', 'A like-for-like tank replacement in a mechanical room or basement, permit filed and closed by the contractor.', 10, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'water_heater';
delete from public.blueprint_package_levers where package_code = 'water_heater';
delete from public.blueprint_package_photos where package_code = 'water_heater';
delete from public.blueprint_package_milestones where package_code = 'water_heater';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Town permits', 'filed by the contractor', 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Decommissioning the old unit', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Installing the new unit', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Testing', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Inspection, town approval, permit closed', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Insurance coverage', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Warranty', null, 70);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('water_heater', 'Haul-away & disposal', null, 80);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('water_heater', 'tank', 'Tank size', 'seg', 'How many people live in the house? That sets the tank size.', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('40', '40 gal', 0, true, '1–2', 10),
  ('50', '50 gal', 16000, false, '3–4', 20),
  ('75', '75 gal', 42000, false, '5 or more', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('water_heater', 'fuel', 'Fuel', 'seg', 'Is your heater gas or electric? A metal flue pipe on top means gas.', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('gas', 'Gas', 0, true, 'Gas, there''s a pipe on top', 10),
  ('electric', 'Electric', -12000, false, 'Electric, no pipe', 20),
  ('tankless', 'Tankless', 145000, false, 'I want tankless', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('water_heater', 'location', 'Location', 'radio', 'Is the new heater going where the old one is, or somewhere else?', 30) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('same', 'Same spot as the old one', 0, true, 'Same spot', 10),
  ('move', 'Move it somewhere else', 65000, false, 'Move it', 20)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('water_heater', 'access', 'Access', 'seg', 'Is it easy to get to, or tucked in a crawlspace or attic?', 40) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('easy', 'Easy', 0, true, 'Easy', 10),
  ('tight', 'Tight (crawlspace, attic)', 18000, false, 'Tight', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('water_heater', 'unit', 'The current unit', 'Label and pipes in frame if you can.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('water_heater', 'space', 'The space around it', 'Step back so the walls, pipes and any stairs are in frame.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A licensed plumber took the job at the community price.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'permit_meeting', 'payment', 'Permit meeting & signing', 3, 10, 'within a week', 'You meet the contractor to sign the town forms. 10% is due at this meeting, paid to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'permit_issued', 'task', 'Permit issued', 4, null, '2–4 wks', 'The town issues the permit.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'work_done', 'payment', 'Work done', 5, 90, '1 day', 'Old unit out, new unit in and tested. The balance is due to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'inspection', 'task', 'Inspection passed', 6, null, '1–2 wks', 'The town inspector signs off and the permit is closed.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('water_heater', 'done', 'done', 'Done', 7, null, null, 'Hot water, permit closed, inspector gone.');

-- Toilet replacement
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('toilet', 'Toilet replacement', 'Toilet', 'replacement', 'Plumbing', 'front', 'priced', 54000, 'Standard height, one toilet, old one hauled away',
        false, null, true, null, 'toilet', 'Remove the old toilet, set a new one on a fresh wax ring, test for leaks, take the old one away.', 20, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'toilet';
delete from public.blueprint_package_levers where package_code = 'toilet';
delete from public.blueprint_package_photos where package_code = 'toilet';
delete from public.blueprint_package_milestones where package_code = 'toilet';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'New toilet, standard height', 'supplied by the contractor', 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'Removing the old toilet', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'New wax ring, bolts and supply line', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'Setting and levelling', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'Leak test', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'Insurance coverage', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'Warranty', null, 70);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('toilet', 'Haul-away & disposal', null, 80);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('toilet', 'height', 'Height', 'seg', 'Standard height, or the taller comfort height?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('standard', 'Standard', 0, true, 'Standard', 10),
  ('comfort', 'Comfort height', 6000, false, 'Comfort height', 20)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('toilet', 'count', 'How many', 'seg', 'How many toilets are we replacing?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('1', '1', 0, true, 'One', 10),
  ('2', '2', 46000, false, 'Two', 20),
  ('3', '3', 90000, false, 'Three', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('toilet', 'supply', 'Who buys the toilet', 'radio', 'Should the contractor bring the toilet, or have you already got one?', 30) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('contractor', 'Contractor supplies it', 0, true, 'Contractor brings it', 10),
  ('owner', 'I already have one', -22000, false, 'I have one', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('toilet', 'toilet', 'The toilet', 'Whole thing, tank to floor.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('toilet', 'shutoff', 'The shutoff valve behind it', 'Low on the wall, to the left usually.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('toilet', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('toilet', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A licensed plumber took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('toilet', 'work_done', 'payment', 'Work done', 3, 100, 'half a day', 'New toilet set and leak-tested. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('toilet', 'done', 'done', 'Done', 4, null, null, 'Done.');

-- Faucet replacement
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('faucet', 'Faucet replacement', 'Faucet', 'replacement', 'Plumbing', 'front', 'priced', 32000, 'One kitchen or bathroom faucet, you supply the faucet',
        false, null, true, null, 'faucet', 'Swap a kitchen or bathroom faucet, new supply lines, tested for drips.', 30, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'faucet';
delete from public.blueprint_package_levers where package_code = 'faucet';
delete from public.blueprint_package_photos where package_code = 'faucet';
delete from public.blueprint_package_milestones where package_code = 'faucet';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'Removing the old faucet', null, 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'Installing yours', 'you pick it, they fit it', 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'New supply lines', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'Drip and pressure test', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'Insurance coverage', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'Warranty', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('faucet', 'Old faucet taken away', null, 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('faucet', 'where', 'Where', 'seg', 'Kitchen or bathroom?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('bath', 'Bathroom', 0, true, 'Bathroom', 10),
  ('kitchen', 'Kitchen', 6000, false, 'Kitchen', 20)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('faucet', 'count', 'How many', 'seg', 'How many faucets?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('1', '1', 0, true, 'One', 10),
  ('2', '2', 24000, false, 'Two', 20)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('faucet', 'supply', 'Who buys the faucet', 'radio', 'Do you have the faucet, or should the contractor bring a good mid-range one?', 30) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('owner', 'I have the faucet', 0, true, 'I have it', 10),
  ('contractor', 'Contractor supplies a mid-range one', 18000, false, 'Bring one', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('faucet', 'faucet', 'The faucet', 'From above, so the holes in the sink show.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('faucet', 'under', 'Under the sink', 'Cabinet door open, valves visible.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('faucet', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('faucet', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A licensed plumber took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('faucet', 'work_done', 'payment', 'Work done', 3, 100, '1–2 hours', 'Fitted and tested. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('faucet', 'done', 'done', 'Done', 4, null, null, 'Done.');

-- Driveway (asphalt)
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('driveway', 'Driveway (asphalt)', 'Driveway', '(asphalt)', 'Hardscaping', 'front', 'priced', 690000, 'Tear-out and repave, about 900 sq ft, 2-car',
        false, null, false, 'Driveways are priced by area, so one of our paving contractors checks yours — by satellite or a drive-by — before the price is final. You''ll approve any change.', 'driveway', 'Remove the old asphalt, regrade and compact the base, lay and roll new asphalt, seal the edges.', 40, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'driveway';
delete from public.blueprint_package_levers where package_code = 'driveway';
delete from public.blueprint_package_photos where package_code = 'driveway';
delete from public.blueprint_package_milestones where package_code = 'driveway';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'Tear-out of the old surface', null, 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'Base regrading and compaction', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'New asphalt, 2 inches compacted', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'Edge sealing', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'Insurance coverage', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'Warranty', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('driveway', 'Haul-away & disposal', null, 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('driveway', 'size', 'Size', 'seg', 'Roughly how big is it? A 2-car driveway is about 900 sq ft.', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('1car', '1-car (~450 sq ft)', -300000, false, '1 car', 10),
  ('2car', '2-car (~900 sq ft)', 0, true, '2 cars', 20),
  ('long', 'Long (~1,400 sq ft)', 380000, false, 'Longer', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('driveway', 'apron', 'Street apron', 'radio', 'Should we redo the apron where it meets the street?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('no', 'Leave the apron', 0, true, 'Leave it', 10),
  ('yes', 'Redo the apron too', 90000, false, 'Redo it', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('driveway', 'wide', 'The whole driveway from the street', 'Include the garage and the apron. Add measurements in the note if you have them.', 10);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('driveway', 'booked', 'booked', 'Requested', 1, null, null, 'You requested the package; a contractor confirms the area first.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('driveway', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A paving contractor confirmed the square footage and took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('driveway', 'work_done', 'payment', 'Work done', 3, 100, '1–2 days', 'Paved and rolled. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('driveway', 'done', 'done', 'Done', 4, null, null, 'Stay off it for three days.');

-- Interior painting
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('interior_painting', 'Interior painting', 'Interior', 'painting', 'Painting', 'front', 'priced', 78000, 'One room, walls only, two coats, you pick the color',
        false, null, true, null, 'painting', 'Walls prepped, patched and painted two coats in a standard room. Paint included.', 50, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'interior_painting';
delete from public.blueprint_package_levers where package_code = 'interior_painting';
delete from public.blueprint_package_photos where package_code = 'interior_painting';
delete from public.blueprint_package_milestones where package_code = 'interior_painting';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('interior_painting', 'Furniture moved and covered', null, 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('interior_painting', 'Patching and light sanding', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('interior_painting', 'Two coats on the walls', 'paint included', 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('interior_painting', 'Clean-up', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('interior_painting', 'Insurance coverage', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('interior_painting', 'Warranty', null, 60);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('interior_painting', 'rooms', 'Rooms', 'seg', 'How many rooms?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('1', '1', 0, true, 'One', 10),
  ('2', '2', 70000, false, 'Two', 20),
  ('3', '3', 135000, false, 'Three', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('interior_painting', 'trim', 'Ceilings & trim', 'seg', 'Walls only, or ceilings and trim too?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('walls', 'Walls only', 0, true, 'Walls only', 10),
  ('ceiling', '+ ceiling', 22000, false, 'Ceiling too', 20),
  ('all', '+ ceiling & trim', 42000, false, 'Everything', 30)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('interior_painting', 'room', 'The room', 'From the doorway, so the size reads.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('interior_painting', 'damage', 'Any damage', 'Cracks, holes, water marks. Skip if none.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('interior_painting', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('interior_painting', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A painter took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('interior_painting', 'work_done', 'payment', 'Work done', 3, 100, '1–2 days', 'Two coats, dry, room put back. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('interior_painting', 'done', 'done', 'Done', 4, null, null, 'Done.');

-- EV charger install
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('ev_charger', 'EV charger install', 'EV charger', 'install', 'Electrical', 'front', 'priced', 125000, 'Level 2, within 25 ft of the panel, charger supplied by you',
        true, 10, true, null, 'ev_charger', 'A dedicated 240 V circuit from your panel to a Level 2 charger in the garage or driveway, permitted and inspected.', 60, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'ev_charger';
delete from public.blueprint_package_levers where package_code = 'ev_charger';
delete from public.blueprint_package_photos where package_code = 'ev_charger';
delete from public.blueprint_package_milestones where package_code = 'ev_charger';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'Town electrical permit', 'filed by the contractor', 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'New 50 A breaker and dedicated circuit', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'Mounting and wiring your charger', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'Testing', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'Inspection, town approval, permit closed', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'Insurance coverage', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('ev_charger', 'Warranty', null, 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('ev_charger', 'distance', 'Run from the panel', 'seg', 'How far is the charger spot from your electrical panel?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('near', 'Under 25 ft', 0, true, 'Close', 10),
  ('mid', '25–60 ft', 45000, false, 'Across the house', 20),
  ('far', 'Over 60 ft', 95000, false, 'Far', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('ev_charger', 'charger', 'Charger', 'radio', 'Do you already have the charger?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('owner', 'I have the charger', 0, true, 'I have it', 10),
  ('contractor', 'Contractor supplies one', 60000, false, 'Bring one', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('ev_charger', 'panel', 'Electrical panel', 'Door open, breakers legible — the electrician reads the amperage off it.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('ev_charger', 'spot', 'Where the charger goes', 'Wall or post, with the car''s parking spot in frame.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A licensed electrician took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'permit_meeting', 'payment', 'Permit meeting & signing', 3, 10, 'within a week', 'You sign the town forms. 10% is due at this meeting, paid to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'permit_issued', 'task', 'Permit issued', 4, null, '1–3 wks', 'The town issues the electrical permit.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'work_done', 'payment', 'Work done', 5, 90, 'half a day', 'Circuit run, charger mounted and tested. The balance is due to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'inspection', 'task', 'Inspection passed', 6, null, '1–2 wks', 'The town inspector signs off.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('ev_charger', 'done', 'done', 'Done', 7, null, null, 'Plug in.');

-- Standby generator
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('generator', 'Standby generator', 'Standby', 'generator', 'Electrical', 'front', 'priced', 1180000, '22 kW whole-house, natural gas, transfer switch, pad',
        true, 10, true, null, 'generator', 'A whole-house standby generator on a pad beside the house, gas line, automatic transfer switch, permits and inspections.', 70, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'generator';
delete from public.blueprint_package_levers where package_code = 'generator';
delete from public.blueprint_package_photos where package_code = 'generator';
delete from public.blueprint_package_milestones where package_code = 'generator';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Town electrical, plumbing and zoning permits', 'filed by the contractor', 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Concrete pad', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Generator, delivered and set', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Gas line from the meter', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Automatic transfer switch', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Start-up and load test', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Inspections, town approval, permits closed', null, 70);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Insurance coverage', null, 80);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('generator', 'Warranty', null, 90);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('generator', 'size', 'Size', 'seg', 'Whole house, or just the essentials?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('14', '14 kW essentials', -240000, false, 'Essentials', 10),
  ('22', '22 kW whole house', 0, true, 'Whole house', 20),
  ('26', '26 kW large home', 210000, false, 'Big house', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('generator', 'gas', 'Gas', 'seg', 'Natural gas from the street, or propane?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('natural', 'Natural gas', 0, true, 'Natural gas', 10),
  ('propane', 'Propane', 120000, false, 'Propane', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('generator', 'panel', 'Electrical panel', 'Door open, breakers legible.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('generator', 'meter', 'Gas meter', 'Generators sometimes need a bigger gas line. The photo tells the contractor before they quote.', 20);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('generator', 'spot', 'Where it should go', 'Along the house, with the windows nearest it in frame.', 30);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A licensed electrician took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'permit_meeting', 'payment', 'Permit meeting & signing', 3, 10, 'within a week', 'You sign the town forms. 10% is due at this meeting, paid to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'permit_issued', 'task', 'Permits issued', 4, null, '3–6 wks', 'The town issues the permits.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'work_done', 'payment', 'Work done', 5, 90, '2–3 days', 'Set, wired, gas connected, load-tested. The balance is due to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'inspection', 'task', 'Inspections passed', 6, null, '2–3 wks', 'Electrical, plumbing and final inspections signed off.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('generator', 'done', 'done', 'Done', 7, null, null, 'Next outage, you won''t notice.');

-- Gutter cleaning & minor repair
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('gutters', 'Gutter cleaning & minor repair', 'Gutter cleaning', '& minor repair', 'Gutters', 'front', 'priced', 34000, 'Single-family, 2 stories, all gutters and downspouts',
        false, null, true, null, 'gutters', 'Every gutter and downspout cleared and flushed, loose hangers re-secured, small leaks sealed.', 80, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'gutters';
delete from public.blueprint_package_levers where package_code = 'gutters';
delete from public.blueprint_package_photos where package_code = 'gutters';
delete from public.blueprint_package_milestones where package_code = 'gutters';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'All gutters cleared by hand', null, 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'Downspouts flushed', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'Loose hangers re-secured', 'up to 6', 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'Small leaks sealed', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'Debris bagged and removed', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'Insurance coverage', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('gutters', 'Warranty', '90 days on repairs', 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('gutters', 'stories', 'Stories', 'seg', 'How many stories is the house?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('1', '1', -10000, false, 'One', 10),
  ('2', '2', 0, true, 'Two', 20),
  ('3', '3', 16000, false, 'Three', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('gutters', 'guards', 'Gutter guards', 'radio', 'Do you have gutter guards on now?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('no', 'No guards', 0, true, 'No guards', 10),
  ('yes', 'Guards on (removed and refitted)', 9000, false, 'Yes, guards', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('gutters', 'front', 'Front of the house', 'From the sidewalk, roofline in frame.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('gutters', 'problem', 'Any problem spot', 'Overflowing corner, sagging run. Skip if none.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('gutters', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('gutters', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A gutter crew took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('gutters', 'work_done', 'payment', 'Work done', 3, 100, '2–3 hours', 'Cleared, flushed, hangers fixed. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('gutters', 'done', 'done', 'Done', 4, null, null, 'Done.');

-- Blinds & shades installation
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('blinds', 'Blinds & shades installation', 'Blinds & shades', 'installation', 'Handyman', 'front', 'priced', 24000, 'Up to 5 windows, blinds you already bought, inside mount',
        false, null, true, null, 'blinds', 'Your blinds or shades measured, mounted level and tested, packaging taken away.', 85, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'blinds';
delete from public.blueprint_package_levers where package_code = 'blinds';
delete from public.blueprint_package_photos where package_code = 'blinds';
delete from public.blueprint_package_milestones where package_code = 'blinds';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Brackets mounted level, inside or outside the frame', null, 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Blinds hung, cords and wands fitted', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Each one tested up and down', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Child-safety cord cleats where needed', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Packaging taken away', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Insurance coverage', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('blinds', 'Warranty', '90 days on the mounting', 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('blinds', 'count', 'How many windows', 'seg', 'How many windows are we doing?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('5', 'Up to 5', 0, true, 'Up to five', 10),
  ('10', '6–10', 20000, false, 'Six to ten', 20),
  ('15', '11–15', 40000, false, 'More than ten', 30)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('blinds', 'supply', 'Who buys the blinds', 'radio', 'Do you have the blinds already, or should the contractor measure and bring standard ones?', 20) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('owner', 'I have them', 0, true, 'I have them', 10),
  ('contractor', 'Measure and supply standard cordless blinds', 42000, false, 'Bring them', 20)
) as v(key, label, delta, dflt, chip, ord);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('blinds', 'motor', 'Motorized', 'radio', 'Any motorized shades? They take a little longer to set up and pair.', 30) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('no', 'No, manual', 0, true, 'Manual', 10),
  ('yes', 'Yes, motorized (setup and pairing)', 15000, false, 'Motorized', 20)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('blinds', 'window', 'One of the windows', 'Whole frame in view, so the mount depth reads.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('blinds', 'blinds', 'The blinds, still boxed', 'The label with the size is enough.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('blinds', 'booked', 'booked', 'Booked', 1, null, null, 'You booked the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('blinds', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A handyman from the community took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('blinds', 'work_done', 'payment', 'Work done', 3, 100, '2–3 hours', 'Every blind hung and tested. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('blinds', 'done', 'done', 'Done', 4, null, null, 'Done.');

-- Windows & doors
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('windows_doors', 'Windows & doors', 'Windows & doors', null, 'Supply: Windows', 'more', 'priced', 145000, 'One replacement window, vinyl, standard size, installed',
        false, null, false, 'Window sizes vary; a contractor confirms the opening before the price is final.', 'window', 'A like-for-like replacement window, installed and sealed.', 110, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'windows_doors';
delete from public.blueprint_package_levers where package_code = 'windows_doors';
delete from public.blueprint_package_photos where package_code = 'windows_doors';
delete from public.blueprint_package_milestones where package_code = 'windows_doors';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Measuring and ordering', null, 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Removal of the old unit', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Installing and sealing the new window', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Interior trim touched up', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Insurance coverage', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Warranty', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('windows_doors', 'Haul-away & disposal', null, 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('windows_doors', 'count', 'How many', 'seg', 'How many windows?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('1', '1', 0, true, 'One', 10),
  ('3', '3', 260000, false, 'Three', 20),
  ('6', '6', 620000, false, 'Six', 30)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('windows_doors', 'outside', 'The window from outside', 'Whole frame in view.', 10);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('windows_doors', 'inside', 'The window from inside', 'Sill and trim visible.', 20);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('windows_doors', 'booked', 'booked', 'Requested', 1, null, null, 'You requested the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('windows_doors', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A contractor confirmed the size and took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('windows_doors', 'work_done', 'payment', 'Work done', 3, 100, 'half a day, after the order arrives', 'Installed and sealed. Paid to the contractor on completion.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('windows_doors', 'done', 'done', 'Done', 4, null, null, 'Done.');

-- Deck & fence
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('deck_fence', 'Deck & fence', 'Deck & fence', null, 'Decks', 'more', 'priced', 420000, '100 ft of 6-ft wood privacy fence, installed',
        true, 10, false, 'Fence runs are priced by length; a contractor confirms the line before the price is final.', 'fence', 'A wood privacy fence along one property line, posts set in concrete, permit filed.', 120, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'deck_fence';
delete from public.blueprint_package_levers where package_code = 'deck_fence';
delete from public.blueprint_package_photos where package_code = 'deck_fence';
delete from public.blueprint_package_milestones where package_code = 'deck_fence';
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Town zoning permit', 'filed by the contractor', 10);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Posts set in concrete', null, 20);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Panels and one gate', null, 30);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Old fence removed', null, 40);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Insurance coverage', null, 50);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Warranty', null, 60);
insert into public.blueprint_package_items (package_code, label, detail, sort_order) values ('deck_fence', 'Haul-away & disposal', null, 70);
with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values ('deck_fence', 'length', 'Length', 'seg', 'Roughly how long is the run?', 10) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
  ('50', '50 ft', -200000, false, '50 ft', 10),
  ('100', '100 ft', 0, true, '100 ft', 20),
  ('200', '200 ft', 400000, false, '200 ft', 30)
) as v(key, label, delta, dflt, chip, ord);
insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values ('deck_fence', 'line', 'The fence line', 'Stand at one end and shoot down the line.', 10);
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('deck_fence', 'booked', 'booked', 'Requested', 1, null, null, 'You requested the package.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('deck_fence', 'accepted', 'accepted', 'Contractor accepted', 2, null, '24–48 h', 'A fence contractor confirmed the run and took the job.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('deck_fence', 'permit_meeting', 'payment', 'Permit meeting & signing', 3, 10, 'within a week', 'You sign the zoning forms. 10% is due at this meeting, paid to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('deck_fence', 'permit_issued', 'task', 'Permit issued', 4, null, '2–4 wks', 'The town issues the permit.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('deck_fence', 'work_done', 'payment', 'Work done', 5, 90, '2–3 days', 'Fence up, gate hung. The balance is due to the contractor.');
insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values ('deck_fence', 'done', 'done', 'Done', 6, null, null, 'Done.');

-- Siding
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('siding', 'Siding', 'Siding', null, 'Siding', 'more', 'coming_soon', null, null,
        true, 10, false, null, 'siding', null, 130, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'siding';
delete from public.blueprint_package_levers where package_code = 'siding';
delete from public.blueprint_package_photos where package_code = 'siding';
delete from public.blueprint_package_milestones where package_code = 'siding';

-- Solar
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('solar', 'Solar', 'Solar', null, 'Electrical', 'more', 'coming_soon', null, null,
        true, 10, false, null, 'solar', null, 140, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'solar';
delete from public.blueprint_package_levers where package_code = 'solar';
delete from public.blueprint_package_photos where package_code = 'solar';
delete from public.blueprint_package_milestones where package_code = 'solar';

-- Basement finishing
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('basement', 'Basement finishing', 'Basement finishing', null, 'General Contractor', 'more', 'coming_soon', null, null,
        true, 10, false, null, 'basement', null, 150, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'basement';
delete from public.blueprint_package_levers where package_code = 'basement';
delete from public.blueprint_package_photos where package_code = 'basement';
delete from public.blueprint_package_milestones where package_code = 'basement';

-- Kitchen
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('kitchen', 'Kitchen', 'Kitchen', null, 'General Contractor', 'more', 'quote', null, null,
        true, 10, false, null, 'kitchen', 'Kitchens can''t be priced blind. Tell us what you have in mind and a person comes back with a quote.', 160, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'kitchen';
delete from public.blueprint_package_levers where package_code = 'kitchen';
delete from public.blueprint_package_photos where package_code = 'kitchen';
delete from public.blueprint_package_milestones where package_code = 'kitchen';

-- Bathroom
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('bathroom', 'Bathroom', 'Bathroom', null, 'General Contractor', 'more', 'quote', null, null,
        true, 10, false, null, 'bathroom', 'Bathrooms can''t be priced blind. Tell us what you have in mind and a person comes back with a quote.', 170, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'bathroom';
delete from public.blueprint_package_levers where package_code = 'bathroom';
delete from public.blueprint_package_photos where package_code = 'bathroom';
delete from public.blueprint_package_milestones where package_code = 'bathroom';

-- Something else
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values ('something_else', 'Something else', 'Something else', 'Tell us in a sentence', 'Handyman', 'more', 'custom', null, null,
        false, null, false, null, 'something_else', 'Not on the grid? Say what it is in a sentence. A person reads it and comes back to you.', 999, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = 'something_else';
delete from public.blueprint_package_levers where package_code = 'something_else';
delete from public.blueprint_package_photos where package_code = 'something_else';
delete from public.blueprint_package_milestones where package_code = 'something_else';

commit;
