-- 019 - the prose audit reaches the actions table too.
--
-- 018 taught fn_log_change to keep prose. A test then proved it did NOT close
-- the gap that started this: `actions` is the ONE table that does not use the
-- shared logger. 65 tables use fn_log_change -> change_events; actions alone
-- uses log_action_event -> action_events, exactly as rulebook 33 requires
-- (one logger per table). So the very edit that exposed the problem - renaming
-- an action and rewriting its notes - was still leaving no trace.
--
-- ONE BODY TABLE, NOT TWO. change_bodies now carries a nullable key to either
-- log, with a check that exactly one is set. Two body tables would have meant
-- two purges, two retention settings and two chances to forget one - and the
-- point of this design is that cleanup stays a single lever.

alter table public.change_bodies
  add column if not exists id bigint generated by default as identity,
  add column if not exists action_event_id uuid references public.action_events(id) on delete cascade;

alter table public.change_bodies drop constraint if exists change_bodies_pkey;
alter table public.change_bodies alter column change_event_id drop not null;
alter table public.change_bodies add primary key (id);

create unique index if not exists change_bodies_change_event on public.change_bodies (change_event_id) where change_event_id is not null;
create unique index if not exists change_bodies_action_event on public.change_bodies (action_event_id) where action_event_id is not null;

alter table public.change_bodies drop constraint if exists change_bodies_one_source;
alter table public.change_bodies add constraint change_bodies_one_source
  check ((change_event_id is not null)::int + (action_event_id is not null)::int = 1);

comment on table public.change_bodies is
  'The before/after TEXT of a prose change, for EITHER log: change_events (65 tables) or action_events (the actions table, which has its own logger per rulebook 33). Disposable by design - the matching event row records that the field changed and stays forever, so deleting a body loses detail and never loses the fact. Pruned by purge_change_bodies() on config.audit_body_retention_days. A missing body means NOT RETAINED, never "unchanged".';

create or replace function public.log_action_event()
returns trigger
language plpgsql
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_actor text;
  v_prose text[] := array['action','notes','desired_outcome','pending_reason'];
  v_key text; v_from text; v_to text; v_id uuid;
  v_cap constant integer := 20000;
begin
  if TG_OP = 'INSERT' then
    insert into action_events(action_id, event_type, to_value, at, actor)
    values (NEW.id, 'created', NEW.status, coalesce(NEW.created_at, now()),
            coalesce(NEW.created_by, 'system'));

    if NEW.assigned_to is not null then
      insert into action_events(action_id, event_type, from_value, to_value, at, actor)
      values (NEW.id, 'assignment', null, NEW.assigned_to, coalesce(NEW.created_at, now()),
              coalesce(NEW.assigned_by, NEW.created_by, 'system'));
    end if;
    return NEW;
  end if;

  v_actor := coalesce(NEW.last_modified_by, 'system');

  if NEW.status is distinct from OLD.status then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id,
            case when NEW.status in ('Completed','Cancelled','Force Cancelled')
                 then 'closed' else 'status_change' end,
            OLD.status, NEW.status, now(), v_actor);
  end if;

  if NEW.assigned_to is distinct from OLD.assigned_to then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'assignment', OLD.assigned_to, NEW.assigned_to, now(),
            coalesce(NEW.assigned_by, v_actor));
  end if;

  if NEW.target_date is distinct from OLD.target_date then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'target_date_change', OLD.target_date::text, NEW.target_date::text, now(), v_actor);
  end if;

  if NEW.priority is distinct from OLD.priority then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'priority_change', OLD.priority, NEW.priority, now(), v_actor);
  end if;

  if NEW.project_id is distinct from OLD.project_id then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'project_change', OLD.project_id::text, NEW.project_id::text, now(), v_actor);
  end if;

  if NEW.parent_action_id is distinct from OLD.parent_action_id then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'parent_change', OLD.parent_action_id::text, NEW.parent_action_id::text, now(), v_actor);
  end if;

  if NEW.asset_id is distinct from OLD.asset_id then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'asset_change', OLD.asset_id::text, NEW.asset_id::text, now(), v_actor);
  end if;

  if NEW.assigned_to_persona_id is distinct from OLD.assigned_to_persona_id then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'assignment_persona', OLD.assigned_to_persona_id::text, NEW.assigned_to_persona_id::text, now(), v_actor);
  end if;

  if NEW.assigned_to_contact_id is distinct from OLD.assigned_to_contact_id then
    insert into action_events(action_id, event_type, from_value, to_value, at, actor)
    values (NEW.id, 'assignment_contact', OLD.assigned_to_contact_id::text, NEW.assigned_to_contact_id::text, now(), v_actor);
  end if;

  -- The prose. pending_reason used to be logged in full here; it now takes the
  -- same path as the rest, so nothing on this table is a special case.
  foreach v_key in array v_prose loop
    v_from := case v_key when 'action' then OLD.action when 'notes' then OLD.notes
                         when 'desired_outcome' then OLD.desired_outcome else OLD.pending_reason end;
    v_to   := case v_key when 'action' then NEW.action when 'notes' then NEW.notes
                         when 'desired_outcome' then NEW.desired_outcome else NEW.pending_reason end;
    if v_from is distinct from v_to then
      insert into action_events(action_id, event_type, from_value, to_value, at, actor)
      values (NEW.id, v_key || '_change',
              case when v_from is null then null else length(v_from) || ' chars' end,
              case when v_to   is null then null else length(v_to)   || ' chars' end,
              now(), v_actor)
      returning id into v_id;
      insert into change_bodies(action_event_id, from_value, to_value, truncated)
      values (v_id, left(v_from, v_cap), left(v_to, v_cap),
              coalesce(length(v_from),0) > v_cap or coalesce(length(v_to),0) > v_cap);
    end if;
  end loop;

  return NEW;
end;
$function$;

update public.config set schema_version = schema_version + 1, schema_updated_at = now();
