#!/usr/bin/env node
// Generates db/002_homeowner_seed.sql from src/lib/catalogue.data.json so
// the app's fallback catalogue and the database seed can never disagree.
//   node db/gen-seed.mjs > db/002_homeowner_seed.sql
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(join(here, "../src/catalogue.data.json"), "utf8"));

const q = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v == null ? "null" : String(v));
const b = (v) => (v ? "true" : "false");
const out = [];
out.push(`-- ============================================================================
-- Homeowner app, part 2 of 3: SEED - the launch catalogue.
-- GENERATED by db/gen-seed.mjs from src/lib/catalogue.data.json. Do not edit
-- by hand; edit the JSON and regenerate. Idempotent: re-running replaces
-- each package's children and upserts the package row.
-- ============================================================================
begin;`);

for (const p of data.packages) {
  out.push(`
-- ${p.name}
insert into public.blueprint_packages
  (code, name, tile_title, tile_line2, trade, tile_group, availability, base_price_cents, config_label,
   requires_permit, permit_deposit_pct, instant_book, approval_note, illustration, description, sort_order, created_by)
values (${q(p.code)}, ${q(p.name)}, ${q(p.tile_title)}, ${q(p.tile_line2)}, ${q(p.trade)}, ${q(p.tile_group)}, ${q(p.availability)}, ${n(p.base_price_cents)}, ${q(p.config_label)},
        ${b(p.requires_permit)}, ${n(p.permit_deposit_pct)}, ${b(p.instant_book)}, ${q(p.approval_note)}, ${q(p.illustration)}, ${q(p.description)}, ${n(p.sort_order)}, 'seed 2026-09-07')
on conflict (code) do update set
  name = excluded.name, tile_title = excluded.tile_title, tile_line2 = excluded.tile_line2, trade = excluded.trade,
  tile_group = excluded.tile_group, availability = excluded.availability, base_price_cents = excluded.base_price_cents,
  config_label = excluded.config_label, requires_permit = excluded.requires_permit, permit_deposit_pct = excluded.permit_deposit_pct,
  instant_book = excluded.instant_book, approval_note = excluded.approval_note, illustration = excluded.illustration,
  description = excluded.description, sort_order = excluded.sort_order, last_modified_at = now(), last_modified_by = 'seed';
delete from public.blueprint_package_items where package_code = ${q(p.code)};
delete from public.blueprint_package_levers where package_code = ${q(p.code)};
delete from public.blueprint_package_photos where package_code = ${q(p.code)};
delete from public.blueprint_package_milestones where package_code = ${q(p.code)};`);
  p.items.forEach((it, i) => {
    out.push(`insert into public.blueprint_package_items (package_code, label, detail, sort_order) values (${q(p.code)}, ${q(it.label)}, ${q(it.detail)}, ${(i + 1) * 10});`);
  });
  p.levers.forEach((l, i) => {
    out.push(`with lv as (insert into public.blueprint_package_levers (package_code, key, label, control, question, sort_order) values (${q(p.code)}, ${q(l.key)}, ${q(l.label)}, ${q(l.control)}, ${q(l.question)}, ${(i + 1) * 10}) returning id)
insert into public.blueprint_package_lever_options (lever_id, key, label, price_delta_cents, is_default, chip, sort_order)
select lv.id, v.key, v.label, v.delta, v.dflt, v.chip, v.ord from lv, (values
${l.options.map((o, j) => `  (${q(o.key)}, ${q(o.label)}, ${n(o.price_delta_cents)}, ${b(o.is_default)}, ${q(o.chip)}, ${(j + 1) * 10})`).join(",\n")}
) as v(key, label, delta, dflt, chip, ord);`);
  });
  p.photos.forEach((ph, i) => {
    out.push(`insert into public.blueprint_package_photos (package_code, key, label, hint, sort_order) values (${q(p.code)}, ${q(ph.key)}, ${q(ph.label)}, ${q(ph.hint)}, ${(i + 1) * 10});`);
  });
  p.milestones.forEach((m) => {
    out.push(`insert into public.blueprint_package_milestones (package_code, key, kind, name, sequence_no, percent_of_contract, typical_range, trigger_description) values (${q(p.code)}, ${q(m.key)}, ${q(m.kind)}, ${q(m.name)}, ${n(m.sequence_no)}, ${n(m.percent_of_contract)}, ${q(m.typical_range)}, ${q(m.trigger_description)});`);
  });
}
out.push(`
commit;`);
process.stdout.write(out.join("\n") + "\n");
